# Generated by Django 2.2.3 on 2019-07-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_auto_20190711_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='date_of_create_equipment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
