# Generated by Django 2.2.3 on 2019-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_auto_20190712_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteequipment',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='favoriteequipment',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
