# Generated by Django 2.2.3 on 2019-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_auto_20190712_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteequipment',
            name='description',
            field=models.TextField(),
        ),
    ]
