# Generated by Django 2.2.3 on 2019-07-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_auto_20190712_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentcategory',
            old_name='equipment',
            new_name='equipments',
        ),
        migrations.AddField(
            model_name='equipment',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.EquipmentCategory'),
        ),
    ]
