# Generated by Django 2.2.3 on 2019-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0009_auto_20190712_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['id', 'name']},
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
