# Generated by Django 2.2.3 on 2019-07-12 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0011_auto_20190712_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentcategory',
            name='updated',
        ),
        migrations.AddField(
            model_name='favoriteequipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteequipment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
