# Generated by Django 2.2.3 on 2019-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0013_auto_20190712_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='favoriteequipment',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images/'),
        ),
    ]
