# Generated by Django 2.2.3 on 2019-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0014_auto_20190712_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(),
        ),
    ]
