# Generated by Django 2.2.3 on 2019-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0015_auto_20190712_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='equipments',
            field=models.ManyToManyField(blank=True, null=True, to='bio.Equipment'),
        ),
    ]
