# Generated by Django 2.2.3 on 2019-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0016_auto_20190712_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='equipments',
            field=models.ManyToManyField(to='bio.Equipment'),
        ),
    ]
