# Generated by Django 2.2.3 on 2019-07-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0017_auto_20190712_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='date_of_create_equipment',
        ),
    ]
