# Generated by Django 2.2.3 on 2019-07-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0021_auto_20190712_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
