# Generated by Django 2.2.3 on 2019-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0022_creator_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='creator',
        ),
        migrations.AddField(
            model_name='equipment',
            name='creators',
            field=models.ManyToManyField(to='bio.Creator'),
        ),
    ]
