# Generated by Django 2.2.3 on 2019-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0023_auto_20190712_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='favoriteequipment',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
