# Generated by Django 2.2.3 on 2019-07-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0028_creator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='equipment_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.Equipment'),
        ),
    ]
