# Generated by Django 2.2.3 on 2019-07-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0029_creator_equipment_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='equipment_creator',
        ),
    ]
