# Generated by Django 2.2.3 on 2019-07-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0030_remove_creator_equipment_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='creators',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
