# Generated by Django 2.2.3 on 2019-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0032_equipmentuseful'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentuseful',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='company',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='created',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='image',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='updated',
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='equipments',
            field=models.ManyToManyField(to='bio.Equipment'),
        ),
    ]
