# Generated by Django 2.2.3 on 2019-07-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0034_auto_20190712_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='equipments',
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='equipments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.Equipment'),
        ),
    ]
