# Generated by Django 2.2.3 on 2019-07-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0035_auto_20190712_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentuseful',
            old_name='equipments',
            new_name='equipment',
        ),
    ]
