# Generated by Django 2.2.3 on 2019-07-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0036_auto_20190712_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
    ]
