# Generated by Django 2.2.3 on 2019-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0037_remove_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.TextField(default='http://192.168.1.103:8000/static/images/placeholder.jpg'),
        ),
        migrations.AlterField(
            model_name='favoriteequipment',
            name='image',
            field=models.TextField(default='http://192.168.1.103:8000/static/images/placeholder.jpg'),
        ),
    ]
