# Generated by Django 2.2.3 on 2019-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0038_auto_20190712_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='equipmentuseful',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='image',
            field=models.TextField(default='http://192.168.1.103:8000/static/images/placeholder.jpg'),
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
