# Generated by Django 2.2.3 on 2019-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0039_auto_20190712_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuseful',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipmentuseful',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
