# Generated by Django 2.2.3 on 2019-07-12 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0040_auto_20190712_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='company',
        ),
        migrations.AddField(
            model_name='equipment',
            name='link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
