# Generated by Django 2.2.3 on 2019-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0044_auto_20190713_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
