# Generated by Django 2.2.3 on 2019-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0045_magazine_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
