# Generated by Django 2.2.3 on 2019-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0046_auto_20190713_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='number',
        ),
        migrations.AddField(
            model_name='magazineinfo',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
