# Generated by Django 2.2.3 on 2019-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0048_auto_20190713_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='equipments',
            field=models.ManyToManyField(blank=True, null=True, to='bio.Equipment'),
        ),
    ]
