# Generated by Django 2.2.3 on 2019-07-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0050_auto_20190717_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='equipments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.Equipment'),
        ),
    ]
