# Generated by Django 2.2.3 on 2019-07-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0051_auto_20190717_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentcategory',
            old_name='equipments',
            new_name='equipment',
        ),
    ]
