# Generated by Django 2.2.3 on 2019-07-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0053_auto_20190717_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
