# Generated by Django 2.2.3 on 2019-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0054_equipment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
