# Generated by Django 2.2.3 on 2019-07-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0055_auto_20190717_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.EquipmentInfo'),
        ),
    ]
