# Generated by Django 2.2.3 on 2019-07-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0056_auto_20190718_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuseful',
            name='equipment_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bio.EquipmentInfo'),
        ),
    ]
