# Generated by Django 2.2.3 on 2019-07-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0057_equipmentuseful_equipment_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinfo',
            name='title',
        ),
        migrations.AddField(
            model_name='equipmentinfo',
            name='mainTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinfo',
            name='subTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
