# Generated by Django 2.2.3 on 2019-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0058_auto_20190718_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_info',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_info',
            field=models.ManyToManyField(to='bio.EquipmentInfo'),
        ),
        migrations.RemoveField(
            model_name='equipmentuseful',
            name='equipment_info',
        ),
        migrations.AddField(
            model_name='equipmentuseful',
            name='equipment_info',
            field=models.ManyToManyField(to='bio.EquipmentInfo'),
        ),
    ]
