# Generated by Django 2.2.3 on 2019-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0060_auto_20190718_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInfoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipmentinfo',
            name='mainTitle',
        ),
        migrations.RemoveField(
            model_name='equipmentinfo',
            name='subTitle',
        ),
        migrations.AddField(
            model_name='equipmentinfo',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='equipmentinfo',
            name='Equipments_items',
            field=models.ManyToManyField(to='bio.EquipmentInfoItems'),
        ),
    ]
