# Generated by Django 2.2.3 on 2019-07-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0061_auto_20190718_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
