# Generated by Django 2.2.3 on 2019-07-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0062_auto_20190718_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='equipmentinfo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='equipmentinfoitems',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='equipmentuseful',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='favoriteequipment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='magazineinfo',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipments_info',
            field=models.ManyToManyField(blank=True, to='bio.EquipmentInfo'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='Equipments_items',
            field=models.ManyToManyField(blank=True, to='bio.EquipmentInfoItems'),
        ),
        migrations.AlterField(
            model_name='equipmentinfoitems',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipmentinfoitems',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
