# Generated by Django 2.2.3 on 2019-07-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0063_auto_20190719_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bio.EquipmentCategory'),
        ),
    ]
