# Generated by Django 2.2.3 on 2019-07-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0064_auto_20190719_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='equipment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
