# Generated by Django 2.2.3 on 2019-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0068_remove_equipmentuseful_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuseful',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipmentuseful',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
